Algoritmo "2.6"

// Autor(a)    :murillo dorsa
// Data atual  : 10/12/2024
Var
   // Seção de Declarações das variáveis
    valor1, valor2:real
Inicio
      escreva("Digite o primeiro valor: ")
    leia(valor1)
    escreva("Digite o segundo valor: ")
    leia(valor2)

    // Verificação e exibição do maior valor
    se valor1 > valor2 então
        escreva("O maior valor é: ", valor1)
    senao
        escreva("O maior valor é: ", valor2)
    fimse



Fimalgoritmo