algoritmo "3,1"
//nome:murillo dorsa
var
   A:inteiro
  B:inteiro



inicio
    escreva("Digite o valor de A: ")
    leia(A)
    escreva("Digite o valor de B: ")
    leia(B)

    // Comparação usando a estrutura "se"
    escreva("Resultado da comparação: ")
    se A > B então
        escreva("A é maior que B")
    senao
        escreva("A não é maior que B")
    fimse

fimalgoritmo
