Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : fernanda
// Descrição   : treiceira atividade(função)
// Autor(a)    : murillo dorsa costa perereira
// Data atual  : 04/12/2024
Var
// Seção de Declarações das variáveis 
 um: inteiro
 altura: inteiro
 base: inteiro


Inicio
escreva("insira um numero :")
leia(um)

se (um >0)então
escreva("positivo")
senao
escreva("negativo")
fimse






Fimalgoritmo