Algoritmo "2.1"

// Autor(a)    : murillo dorsa
// Data atual  : 09/12/2024
Var
   // Seção de Declarações das variáveis
   modo: inteiro
   modo1: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("insira o valor de retiro: ")
   leia(modo)

   se(modo >=10)entao
      escreval("é maior que 10")
   fimse

   se(modo <=10)entao
      escreval("não é maior que 10")
   fimse





Fimalgoritmo