algoritmo "Divisão com validação"
var
//murillo dorsa
   valor1, valor2: inteiro
    resultado:real
inicio
   // Leitura do primeiro valor
   escreval("Digite o primeiro valor: ")
   leia(valor1)
   

    valor2 <- 0
    enquanto valor2=0 faca
    escreva("digite um valor diferente que zero")
    leia(valor2)
    
    fimenquanto
    
    resultado <- valor1 / valor2
    escreva("o resultado é: ",resultado)
    leia(resultado)


   fimalgoritmo