Algoritmo "8.4"
//murillo dorsa
Var
// Seção de Declarações das variáveis 
    i: inteiro
   quadrado: inteiro


Inicio



   // Seção de Comandos, procedimento, funções, operadores, etc...

   i <- 15

    /
    enquanto i <= 200 faça
        quadrado <- i * i
        escreva("O quadrado de ", i, " é ", quadrado, "\n")
        i <- i + 1
    fimEnquanto
Fimalgoritmo















