Algoritmo "0.1"

// Autor(a)    :murillo dorsa
// Data atual  : 10/12/2024
Var
   // Seção de Declarações das variáveis
     numero:inteiro
     numero1:inteiro
     resultado:inteiro

Inicio

escreval("escreva um numero: ")
leia(numero)
escreval("escreva outro numero: ")
leia(numero1)

resultado <- numero + numero1

escreval("o seu resultado :", resultado)




Fimalgoritmo