Algoritmo "1.1"

// Autor(a)    : murillo dorsa
// Data atual  : 06/12/2024
Var
// Seção de Declarações das variáveis
   numero:inteiro
   numero1:inteiro
   resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreva ("Lucas recebeu qual valor da parcela do sálario?")
    Leia (numero)
    
    resultado<-(numero+1)
    Escreva ("recebeu o valor de:", resultado)

Fimalgoritmo